server:
  port: 9090
  servlet:
    context-path: /api/v1

spring:
  application:
    name: acnecare-app-api
  datasource:
    url: ${DATABASE_URL:jdbc:mysql://localhost:3306/acnecare_app_api}
    username: ${DATABASE_USERNAME:root}
    password: ${DATABASE_PASSWORD:root}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  signer-key: ${JWT_SIGNER_KEY:fb886b389ba6cd149a7deef483af664b62ff17776eb0d04a991251c0e4fba92e}
  access-token-valid-duration: ${ACCESS_TOKEN_VALID_DURATION:900}
  refresh-token-valid-duration: ${REFRESH_TOKEN_VALID_DURATION:604800}

auth:
  cookie:
    access-token-name: "access_token"
    refresh-token-name: "refresh_token"
    http-only: true
    secure: ${AUTH_COOKIE_SECURE:false}
    same-site: ${AUTH_COOKIE_SAME_SITE:Lax}
    max-access-token-age: 900
    max-refresh-token-age: 604800
    access-path: /
    refresh-path: /api/v1/auth

cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:5173}